/**
 * Database types, hand-maintained against db/migrations/.
 *
 * This was generated by the Supabase CLI. It keeps the same `Database` and
 * `Constants` shape on purpose: roughly forty call sites reference
 * `Database["public"]["Enums"][...]` and `Constants.public.Enums.*`, and keeping
 * the public surface identical meant the move off Supabase touched none of
 * them. Same reasoning as keeping the name `auth.uid()` in the schema.
 *
 * The old file was 452 lines of generated Insert/Update/Relationships variants
 * the app never used. This is the part that was actually referenced.
 *
 * When db/migrations/ changes, change this too.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

const AI_RECOMMENDATION = ["STRONG", "MODERATE", "WEAK"] as const;
const APPLICATION_STAGE = [
  "APPLIED",
  "SCREENED",
  "TECH_INTERVIEW",
  "FINAL",
  "OFFER",
  "REJECTED",
] as const;
const EMPLOYMENT_TYPE = ["FULL_TIME", "PART_TIME", "CONTRACT"] as const;
const JOB_CATEGORY = [
  "SOFTWARE_ENGINEERING",
  "DATA_AI",
  "DESIGN",
  "PRODUCT",
  "MARKETING",
  "SALES",
  "FINANCE_ACCOUNTING",
  "OPERATIONS",
  "CUSTOMER_SUPPORT",
  "HEALTHCARE",
  "EDUCATION",
  "ENGINEERING_TRADES",
  "LEGAL",
  "WRITING_CONTENT",
  "OTHER",
] as const;
const JOB_STATUS = ["OPEN", "CLOSED"] as const;
const SALARY_PERIOD = ["HOURLY", "MONTHLY", "ANNUAL"] as const;
const SCREENING_STATUS = ["PENDING", "PROCESSING", "DONE", "ERROR"] as const;
const USER_ROLE = ["APPLICANT", "EMPLOYER"] as const;
const WORK_MODE = ["REMOTE", "ONSITE", "HYBRID"] as const;

export const Constants = {
  public: {
    Enums: {
      ai_recommendation: AI_RECOMMENDATION,
      application_stage: APPLICATION_STAGE,
      employment_type: EMPLOYMENT_TYPE,
      job_category: JOB_CATEGORY,
      job_status: JOB_STATUS,
      salary_period: SALARY_PERIOD,
      screening_status: SCREENING_STATUS,
      user_role: USER_ROLE,
      work_mode: WORK_MODE,
    },
  },
} as const;

type ProfilesRow = {
  id: string;
  role: (typeof USER_ROLE)[number];
  full_name: string | null;
  company_name: string | null;
  phone: string | null;
  resume_path: string | null;
  resume_filename: string | null;
  resume_uploaded_at: string | null;
  preferred_categories: (typeof JOB_CATEGORY)[number][];
  onboarded_at: string | null;
  created_at: string;
};

type JobsRow = {
  id: string;
  employer_id: string;
  title: string;
  description: string;
  requirements: string;
  location: string | null;
  salary_min: number | null;
  salary_max: number | null;
  salary_period: (typeof SALARY_PERIOD)[number];
  employment_type: (typeof EMPLOYMENT_TYPE)[number];
  work_mode: (typeof WORK_MODE)[number];
  category: (typeof JOB_CATEGORY)[number];
  status: (typeof JOB_STATUS)[number];
  expires_at: string | null;
  created_at: string;
};

type ApplicationsRow = {
  id: string;
  job_id: string;
  applicant_id: string;
  resume_path: string | null;
  stage: (typeof APPLICATION_STAGE)[number];
  screening_status: (typeof SCREENING_STATUS)[number];
  ai_score: number | null;
  ai_recommendation: (typeof AI_RECOMMENDATION)[number] | null;
  ai_summary: string | null;
  ai_matched: Json | null;
  ai_missing: Json | null;
  ai_flags: Json | null;
  created_at: string;
  updated_at: string;
};

type ApplicationEmailsRow = {
  id: string;
  application_id: string;
  kind: string;
  subject: string;
  body: string;
  sent_by: string | null;
  sent_at: string;
};

export type Database = {
  public: {
    Tables: {
      profiles: { Row: ProfilesRow };
      jobs: { Row: JobsRow };
      applications: { Row: ApplicationsRow };
      application_emails: { Row: ApplicationEmailsRow };
    };
    Enums: {
      ai_recommendation: (typeof AI_RECOMMENDATION)[number];
      application_stage: (typeof APPLICATION_STAGE)[number];
      employment_type: (typeof EMPLOYMENT_TYPE)[number];
      job_category: (typeof JOB_CATEGORY)[number];
      job_status: (typeof JOB_STATUS)[number];
      salary_period: (typeof SALARY_PERIOD)[number];
      screening_status: (typeof SCREENING_STATUS)[number];
      user_role: (typeof USER_ROLE)[number];
      work_mode: (typeof WORK_MODE)[number];
    };
  };
};
